# File: .github/workflows/mlflow_tracking.yml
name: MLflow Tracking Only

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mlflow-track:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Run training & log to MLflow
        env:
          # If you have a remote MLflow server, set its URI here
          # Otherwise runs will log to ./mlruns
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        run: |
          python src/train.py

      - name: Upload MLflow artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-runs
          path: mlruns/
